### ISSUE TITLE
Limit Bandwidth Option

### ISSUE THREAD

**Issue by EntropyGit** [wabbajack-tools/wabbajack#852] opened 2020-05-19 23:00 UTC
I noticed when downloading a modlist Wabbajack will use all of my bandwidth to download the necessary files. This is a good thing if you want to download the files quickly, but not such a good thing when you want to use your PC in the mean time. E.g. watching YouTube.

What I am suggesting is to create a simple slider or a drop down menu which would allow the user to allocate the exact amount of bandwidth for Wabbajack to use. This could be down next to the percent usage if you go with the slider option. Or on the settings menu as a drop down. Or both.

Steam includes a nice intuintive solution, see screenshot below for example.

I hope this gets considered, as it would be a great QOL improvement in my eyes. Thanks.

![0h9ELxqiyt](https://user-images.githubusercontent.com/53876664/82386641-c99d7700-9a2c-11ea-9752-49d74cded7aa.png)

**Comment by tr4wzified** [comment] 2020-05-20 20:42
Duplicate of #57

**Closed** 2020-05-23 13:49 UTC
