### ISSUE TITLE
"Install complete" with a clearly incomplete install

### ISSUE THREAD

**Issue by GravenImages** [wabbajack-tools/wabbajack#2158] opened 2022-11-02 02:57 UTC
**Describe the bug**
I updated a list (living skyrim 4's beta) to the public release from a closed beta, Wabbajack said "Install Complete" (Wabbajack.03.log). Upon opening my shortcut for MO2, it was missing. I checked the install folder and a lot of item were missing, screenshot of the folder attached. Upon running the same .wabbajack file over the same directories resulted in a full re-install of the folder (wabbajack.05.log). This then crashed after calling out a few files as corrupt, seemingly at random since they previously worked just fine.  Trying once more got an "install complete" with the folder looking proper once more (wabbajack.current.log).

**Additional Context**
Windows 11, Skyrim SE

**Wabbajack Version**

3.0.3.1

**Logs**

[Wabbajack.03.log](https://github.com/wabbajack-tools/wabbajack/files/9915160/Wabbajack.03.log)
![Wabbajack issue](https://user-images.githubusercontent.com/81875512/199375630-ffef1a21-57b7-4d10-a77a-7613ca16275c.png)
[Wabbajack.05.log](https://github.com/wabbajack-tools/wabbajack/files/9915503/Wabbajack.05.log)

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9915517/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment] 2022-11-02 21:42
duplicate of #2110

**Closed** 2022-11-02 21:46 UTC
Labels: duplicate
