### ISSUE TITLE
Another issue with WJ Startup Crash with no logs.

### ISSUE THREAD

**Issue by ShadowAce2000** [wabbajack-tools/wabbajack#2463] opened 2023-12-11 16:15 UTC
I'm having a similar problem to the post:
https://github.com/wabbajack-tools/wabbajack/issues/2456

Essentially, running the Wabbajack.exe files just pop up with the logo then closes shortly after, with no view of the actual software sceen, and no logs posted in the folder.

I've deleted, and reinstalled Wabbajack many times, including clearing the local program folder.
Reading the event viewer for the error gives this:

Faulting application name: Wabbajack.exe, version: 3.4.0.0, time stamp: 0x65410000
Faulting module name: System.Private.CoreLib.dll, version: 8.0.23.53103, time stamp: 0x95cd51ed
Exception code: 0x80131623
Fault offset: 0x00000000004286bb
Faulting process id: 0x0x6BA4
Faulting application start time: 0x0x1DA2C4AF1F0CB03
Faulting application path: C:\Modding\Wabbajack\3.4.0.0\Wabbajack.exe
Faulting module path: C:\Modding\Wabbajack\3.4.0.0\System.Private.CoreLib.dll
Report Id: 56fde1ad-2d27-42ac-9686-d7ebc0ac4648
Faulting package full name: 
Faulting package-relative application ID: 

I don't really understand any of this, but it seems to be a separate cause of the issue from the posted link example above.. Any suggestions?

**Comment by EzioTheDeadPoet** [comment] 2023-12-11 16:59
Duplicate of #2456

**Closed by EzioTheDeadPoet** 2023-12-11 16:59 UTC
