### ISSUE TITLE
WJ continues to compile despite it flagging the database disk image as malformed.

### ISSUE THREAD

**Issue by Althro** [wabbajack-tools/wabbajack#2233] opened 2022-11-29 21:53 UTC
**Describe the bug**

There appears to be a bug where WJ will continue to compile a list if the disk image is shown as malformed. This occured after a few successful compiles but on this occurence showed as compilation failed. WJ continued to compile however until I exited. I have attached the log from the session in question.

Upon resetting my WJ installation, the error seemed to pass. Luca advised sharing this however.

**Additional Context**

Win 11 Pro 22H2, SAE Steam Edition.

**Wabbajack Version**

V3.0.4.1

**Logs**

[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/10117637/Wabbajack.00.log)

**Comment by EzioTheDeadPoet** [comment] 2022-12-04 21:54
requested the issue, cause same as now I was tired and couldn't pin point the best intended behavior for an error like that. Or if for example WJ should stop a compile sooner if this error occurs. Or if WJ could automatically purge the malformed database, say so in the log and recommend a retry.

**Comment by EzioTheDeadPoet** [comment] 2023-02-04 07:12
still needs investigating

**Comment by EzioTheDeadPoet** [comment] 2023-06-06 05:10
if this was related to the hash cache it is possible that this was fixed. But since I am not 100% sure I'll keep this issue open.

**Comment by Althro** [comment] 2023-06-06 18:57
I think it most likely was related to it as a WJ reset/relaunch fixed it.

**Comment by EzioTheDeadPoet** [comment] 2023-06-06 19:39
If you are not opposed to it, then I would probably close the issue then.

**Closed** 2023-06-07 19:02 UTC
Labels: enhancement, possible bug
