### ISSUE TITLE
Zmerge binary patched plugins corruption

### ISSUE THREAD

**Issue by NotTotal** [wabbajack-tools/wabbajack#337] opened 2020-01-04 05:37 UTC
**Describe the bug**
Merges that include binary patched ESPs come out corrupted on the install side. Steps to create:
1. install edit an esp file in xedit/CK from the original source
2. build merge including this esp
3. Compile+distribute
4. when end user installs their merge file will be corrupted
5. verify this by trying to load the modlist in xedit and crtl+f the xedit log for error

Workaround by putting WABBAJACK_INCLUDE on the merge in mo2

**Comment by Mdc211** [comment] 2020-01-04 05:51
I can confirm I have experienced this bug also. MCM translations can also get broken.

**Comment by halgari** [comment] 2020-01-06 22:13
Brain-dumping my thoughts on this so I don't forget it later:

I'm pretty sure this is caused by WJ building the patch from the files on disk instead of the source files in the archives. So we should fix this by first patching the source files during install, and then building the zpatch afterwards from the files in the install dir.

**Comment by NotTotal** [comment] 2020-01-09 22:33
Here are two corrupted plugins and their clean versions, as well as the SSEEdit log from trying to launch them
[WJ Corrupted Merges.zip](https://github.com/wabbajack-tools/wabbajack/files/4042839/WJ.Corrupted.Merges.zip)

**Comment by halgari** [comment] 2020-02-21 04:54
@NotTotal Please check this again, I'm pretty sure this was fixed as part of 5db84a6ee68c7721c5b675f319ca2af8a02ac8b6 that Noggog implemented on Jan 18th. At least the bugs he fixed in that merge were implemented to fix exactly the type of corruption I see in your example files.

**Comment by halgari** [comment] 2020-05-30 13:44
closed as I haven't heard about this for months

**Closed by halgari** 2020-05-30 13:44 UTC
Labels: bug
