### ISSUE TITLE
Unable to download FalloutNV.exe TTW

### ISSUE THREAD

**Issue by Dragonborn5301** [wabbajack-tools/wabbajack#2540] opened 2024-04-25 20:16 UTC
**Describe the bug**

When I try to install the "Begin Again - A Tale of Two Wastelands" Modpack for Fallout new Vegas, the Installation always fails after downloading every mod with the description: Unable to download FalloutNV.exe (GameFileSourceDownloader+State|FalloutNewVegas|1.4.0.525|falloutnv.exe). I did a clean installation on both games (Fallout 3:GOTJ and FalloutNV: Ultimate Edition both from Steam) and set the language to english (I live in germany). The Log contains the last couple downloaded mods plus the issue at the end. Can someone please help, thanks in advance.

> **EDIT**(Luca|EzioTheDeadPoet):  
> Removed additional (in this case unneeded) information to make it easier to access the comments for new readers.

**Comment by Mieekaserra** [comment] 2024-04-25 20:23
Most likely, you have the German "no gore" version of fnv.

The list was built using the global version. Wabbajack is failing because the Exe is different.

**Comment by EzioTheDeadPoet** [comment] 2024-04-25 20:25
You need to verify your game files and make sure to follow the full written guide of the list you are installing.
If your vanilla files can't be found then they are not a 1:1 match to what the author has. So something with your file is different, broken or modified.

This is not a bug. It is intended behavior.

You need to either go to the support discord for the list or ask steam support to remove the NV from your steam account (refund probably won't work so have them NUKE it from your account) and buy a global key of the game.

**Comment by Dragonborn5301** [comment] 2024-04-25 20:41
> You need to verify your game files and make sure to follow the full written guide of the list you are installing. If your vanilla files can't be found then they are not a 1:1 match to what the author has. So something with your file is different, broken or modified.
> 
> This is not a bug. It is intended behavior.
> 
> You need to either go to the support discord for the list or ask steam support to remove the NV from your steam account (refund probably won't work so have them NUKE it from your account) and buy a global key of the game.

I did buy the key for FalloutNV: Ultimate Edition on MMOGA, there it says it's the uncut/global version and I remember MR. House splashing open when i shot him back in the good old days and I think you are unable to change the Language of the game when it's the cut version but I can. If I'm wrong can someone tell me where I can get a global copy.

**Comment by EzioTheDeadPoet** [comment] 2024-04-25 20:57
Go on steam:
![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/2ae8aa2f-f468-4cd1-94c7-dc573c007ead)
![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/22733c9f-94fb-4a11-8aaa-6cf775e241d4)

And there search for the full name of the Fallout NV key
Because if it is region specific it "usually" has some indicator like the this bundle for Wolfenstein that includes the censored German copy of the game but also adds the global uncensored version to your account.
![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/d4fbcafb-5dae-41c4-b5c6-d9e9129662b5)


If that says global then you need to go back to read the FULL instructions for the list you are trying to install.

But GitHub IS NOT meant for list specific issues, which this is.

**Comment by Dragonborn5301** [comment] 2024-04-25 21:13
> Go on steam: ![image](https://private-user-images.githubusercontent.com/52624146/325766619-2ae8aa2f-f468-4cd1-94c7-dc573c007ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNzk0MTIsIm5iZiI6MTcxNDA3OTExMiwicGF0aCI6Ii81MjYyNDE0Ni8zMjU3NjY2MTktMmFlOGFhMmYtZjQ2OC00Y2QxLTk0YzctZGM1NzNjMDA3ZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTU1MjAxYjc3YmY3ZjljZDg5MWFjZmFkZmUyMjJhYjVlNjM0ZWI3N2UwODFkNWY5MzA4YzE1ODgyYzRhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYe8mttazDe7i7is5025JW1yMxOigcB-eRigxav3qc4) ![image](https://private-user-images.githubusercontent.com/52624146/325767025-22733c9f-94fb-4a11-8aaa-6cf775e241d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNzk0MTIsIm5iZiI6MTcxNDA3OTExMiwicGF0aCI6Ii81MjYyNDE0Ni8zMjU3NjcwMjUtMjI3MzNjOWYtOTRmYi00YTExLThhYWEtNmNmNzc1ZTI0MWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDM1MzM3ZmNlMTUwNzVmMDM4YTY0Yjg4NjNkODRjN2VhMWQzZGQ1N2NhYzYzZDNiNjM5OTViNDMxMTlhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yyvofTakMDwtQuyQrd5HfcXhqo5jl1WPidukEIzw2Xk)
> 
> And there search for the full name of the Fallout NV key Because if it is region specific it "usually" has some indicator like the this bundle for Wolfenstein that includes the censored German copy of the game but also adds the global uncensored version to your account. ![image](https://private-user-images.githubusercontent.com/52624146/325768082-d4fbcafb-5dae-41c4-b5c6-d9e9129662b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNzk0MTIsIm5iZiI6MTcxNDA3OTExMiwicGF0aCI6Ii81MjYyNDE0Ni8zMjU3NjgwODItZDRmYmNhZmItNWRhZS00MWM0LWI1YzYtZDllOTEyOTY2MmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDIxMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NTcyZjdiM2IxYTlmZDhkOTFhMWQ4ZTJlOGVkNmI3NGU1ODdlMzUwM2IxOTZmMjNkYmVkNTQwZWQxNjMzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qijwy9UcBm6WKRPtPImnCEeM_Pkvx-dMw-OlDdFeAhw)
> 
> If that says global then you need to go back to read the FULL instructions for the list you are trying to install.
> 
> But GitHub IS NOT meant for list specific issues, which this is.

Thanks a lot, I was searching a way to find out how to look that up on Steam. It Says Fallout: New Vegas (DE) so that is clearly the problem. So I found a Site that says Fallout New vegas global key so I'm gonna Nuke the current one and buy that one and try again. And again thanks, have a great day.

**Comment by tr4wzified** [comment] 2024-06-16 15:16
Closing this issue since it's not actually a WJ issue

**Closed by tr4wzified** 2024-06-16 15:16 UTC
Labels: not a bug
