### ISSUE TITLE
WJ uses all available bandwidth to download

### ISSUE THREAD

**Issue by researched** [wabbajack-tools/wabbajack#1419] opened 2021-04-14 17:13 UTC
**Is your feature request related to a problem? Please describe.**
Yes. My internet download speed is touted as 40Mbps. When downloading from Nexus using their free option, it uses 8 threads to download, which totals 45.5 Mbps of my download capacity. Result: everything else comes to a standstill.

**Describe the solution you'd like**
A pause option so one can pause the downloads if something more critical comes up.
AND/OR: a way to reduce the number of download threads, so one can at least give some bandwidth to other apps.
Update: even if one download only one file, WJ uses all available internet bandwidth. An option to limit WJ's download bandwidth usage should allow other apps to get a chance on the internet too.

**Describe alternatives you've considered**
Closing WJ stops all threads, of course. But that means that all downloads that were already in progress (and has take a long time) all stops, and must be redownloaded from scratch next time round. It also takes time to start WJ, and it takes time to compare all the files before it starts downloading again. Lots of time wasted.

**Additional context**
Screenshot of my system's download when downloading:
![image](https://user-images.githubusercontent.com/52639432/114750872-773f0600-9d22-11eb-8945-10ec5222ee40.png)
I was surprised to see this, because I thought Nexus only downloads at 2Mbps for free users.

In hindsight, I discovered that even if one download only one file, WJ will use all available internet bandwidth it can get. That would work great for people with fast internet, but for those of us with slower internet, it prevents one from using the internet for anything else.
Maybe an option to limit WJ's download speed may be a better solution?

**Comment by erri120** [comment] 2021-04-14 17:15
You can limit the amount of threads Wabbajack uses in the options also duplicate of #1359

**Closed by erri120** 2021-04-14 17:15 UTC

**Comment by researched** [comment] 2021-04-14 17:18
Update 2: I just discovered that WJ uses all my internet even if no file downloads are queued! What is it doing with all that bandwidth? Is it a bug?
